# Generated by Django 3.0 on 2020-10-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200917_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
