# Generated by Django 3.0 on 2020-10-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200816_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailactivation',
            options={'verbose_name': 'Email Activation', 'verbose_name_plural': 'Email Activations'},
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'verbose_name': 'Profile Image', 'verbose_name_plural': 'Profile Images'},
        ),
    ]
