# Generated by Django 3.0 on 2020-10-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['is_admin', 'is_author', 'username']},
        ),
    ]
