# Generated by Django 3.0 on 2020-10-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201016_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_admin', '-is_author', 'username']},
        ),
    ]
