# Generated by Django 3.0 on 2020-09-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bloginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogName',
        ),
    ]
