# Generated by Django 3.0 on 2020-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_blogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
