# Generated by Django 3.0 on 2020-10-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200919_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutblog',
            options={'verbose_name': 'About Blog', 'verbose_name_plural': 'About Blog'},
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='bloginfo',
            options={'verbose_name': 'Blog Info', 'verbose_name_plural': 'Blog Info'},
        ),
        migrations.AlterModelOptions(
            name='mianimage',
            options={'verbose_name': 'Mian Image', 'verbose_name_plural': 'Main Images'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy and Policy', 'verbose_name_plural': 'Privacy and Policy'},
        ),
    ]
