# Generated by Django 2.2.1 on 2020-02-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBlog',
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
