# Generated by Django 2.2.1 on 2020-02-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_aboutblog_aboutme_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutblog',
            options={'verbose_name_plural': 'About Blog'},
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy and Policy'},
        ),
    ]
